# These are supported funding model platforms

patreon: gioxx
ko_fi: gioxx
buy_me_a_coffee: gioxx
custom: ["https://www.paypal.me/gioxx", "https://tag.satispay.com/gioxx", "https://go.gioxx.org/acquista"]
