# These are supported funding model platforms

patreon: gioxx
ko_fi: gioxx
custom: ["https://www.paypal.me/gioxx", PayPal]
custom: ["https://tag.satispay.com/gioxx", Satispay]
custom: ["https://www.buymeacoffee.com/gioxx", Buy me a Coffee]
custom: ["https://go.gioxx.org/acquista", Amazon]
