name: NoAds Stable

on:
  schedule:
    - cron: '0 0 */18 * *'

  workflow_dispatch:

jobs:
  noads_stable:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 1

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Rome"

      - name: Set date and time
        run: bash ./sh/parts/datetime.sh

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Make Stable
        run: bash ./sh/make_stable.sh

      - name: Prepare list header
        if: env.stop != 'true'
        run: |
          cp filtri.txt filtri_content.txt
          cat <<EOF > filtri.txt
          [Adblock Plus 2.8]
          ! Title: NoAds X Files
          ! Version: $update
          ! X Files migliora la tua navigazione quotidiana!
          ! Last modified: $lastmodified
          ! Expires: 15 days
          ! Homepage: https://xfiles.noads.it
          ! Blog: https://go.gioxx.org/noads
          ! Hosting: GitHub.com
          !
          EOF
          cat filtri_content.txt >> filtri.txt
          rm filtri_content.txt

      - name: Prepare vCheck
        if: env.stop != 'true'
        run: |
          num_of_lines=$(grep -v '^! ' "filtri.txt" | wc -l)
          md5=$(md5sum filtri.txt | cut -d ' ' -f 1)

          cat <<EOF > vcheck/check_filtri.txt
          $update
          $lastmodified
          $checkwebsite
          $num_of_lines
          $md5
          EOF

      - name: Commit Stable
        if: env.stop != 'true'
        run: |
          git config --local user.email "114237374+GWall-bot@users.noreply.github.com"
          git config --local user.name "GWall[bot]"
          git add filtri.txt vcheck/check_filtri.txt
          git diff --cached --quiet || git commit -m "Aggiornamento Stable (GHA) $update del $lastmodified"

      - name: Push Stable
        if: env.stop != 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
